//LOADING
export const LOADING = 'LOADING';
export const LOADING_ITEM_CATEGORY = 'LOADING_ITEM_CATEGORY';

//API MESSAGES
export const GET_API_MESSAGE = 'GET_API_MESSAGE';
export const CLEAR_API_MESSAGE = 'CLEAR_API_MESSAGE';
// API ERRORS
export const GET_API_ERROR = 'GET_API_ERROR';
export const CLEAR_API_ERROR = 'CLEAR_API_ERROR';

// Auth
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_OUT_USER = 'CLEAR_OUT_USER';

//CATEGORY
export const GET_CATEGORIES_LIST = 'GET_CATEGORIES_LIST';

//SUB CATEGORY
export const GET_SUB_LIST = 'GET_SUB_LIST'; //by categoryId
export const GET_SUB_ALL = 'GET_SUB_ALL'; //get all existing
